### ISSUE TITLE
dgettext_noop/2 is broken in v0.17.3?

### ISSUE THREAD

**Issue by nmbrone** [elixir-gettext/gettext#237]
First of all thanks for all your work.

Seems like the returned value of `dgettext_noop/2` was changed in the last version but the change was not reflected in the documentation. The documentation says: "The return value is the given string, so that this macro can be used seamlessly in place of the string to extract" which is not true anymore since the returned value is a tuple.

The change comes from this PR #228

**Comment by whatyouhide** [comment]
Good catch! It's true, the return value of the `*_noop` macros was accidentally broken. I think it should be enough to switch it back to just return the given string. Would you be willing to send a PR for this? Otherwise I can tackle it in the afternoon or in the next couple days, depending on work 😄

**Comment by josevalim** [comment]
v0.17.4 released with a fix :D

**Comment by whatyouhide** [comment]
Oh, sweet! Thanks so much @josevalim 💟
