### ISSUE TITLE
Can you explain `ex-autogen` consequences?

### ISSUE THREAD

**Issue by fchabouis** [elixir-gettext/gettext#301]
Hi,
I just noticed that translations automatically generated get flagged with `ex-autogen`. I read in the [doc](https://hexdocs.pm/gettext/Mix.Tasks.Gettext.Extract.html) that it allows to automatically remove a translation for the po files if it is not used anymore. Does it mean that the existing translations (created before the existence of the flag) need to be updated with this flag as well?
Thanks

**Comment by josevalim** [comment]
Currently we track both ex-autogen (new) and elixir-format (old), so you should be fine. However, it would be nice if we automatically added ex-autogen to everything appropriate when using a new Gettext version. By your description, I assume it is not happening. Thoughts @maennchen?

**Comment by maennchen** [comment]
@josevalim I think currently we do not merge the flags:

https://github.com/elixir-gettext/gettext/blob/134a27c3ab47145b9c4444873802ebbb8e89addc/lib/gettext/extractor.ex#L342

I'm also not sure if a general flag union would be good since that could re-add manually removed flags.

It could make sense to add a special case to add the `ex-autogen` flag as well as the format flag.

It would probably also be good to mention why the change was made and how the migration path behaves so that people understand.

I'll happily provide the flag merging update if that makes sense to you. I'm not that great at explaining things in a short and specific way. Could you or someone else maybe come up with a good text? I would mention the following points:

* Pre 0.19:
  - the `elixir-format` flag is used to determine the message format
  - the `elixir-format` flag is used to check if the translation is automatically managed and therefore purged.
* Post 0.19:
  - The `elixir-format` flag is only used to determine the message format
  - when switching interpolation, a different format flag is set according to the interpolation module
  - A new flag `ex-autogen` is used to check if a translation is automatically managed
  - (Deprecated) the `elixir-format` flag is also used to check if automatic, but only to not break older projects
  - (Depending on the proposal above) When updating to a new version and extracting again, the `ex-autogen` flag will be added to all automatic translations

**Comment by josevalim** [comment]
> (Depending on the proposal above) When updating to a new version and extracting again, the ex-autogen flag will be added to all automatic translations

Yes, I think we should probably do this otherwise we will never be able to remove the current "elixir-format" flag check. :)

**Comment by maennchen** [comment]
@josevalim I'll create a small PR for this :+1:

**Comment by fchabouis** [comment]
Thanks a lot for the reactivity :heart:
