### ISSUE TITLE
Locale changes between static mount and liveview

### ISSUE THREAD

**Issue by itrelease** [elixir-gettext/gettext#386]
I'm a bit confused how this is happens, so for initial render I get resolved locale `en_US` but when I get mounted liveview it changes locale to default `en`. The only place I set locale is in my custom plug — `set_locale_plug.ex`:

```elixir
defmodule JobtodayWeb.Plugs.SetLocalePlug do
  import Plug.Conn

  @supported_locales Gettext.known_locales(JobtodayWeb.Gettext)

  @spec init(String.t()) :: String.t()
  def init(default_locale), do: default_locale

  @spec call(Plug.Conn.t(), String.t()) :: Plug.Conn.t()
  def call(conn, default_locale) do
    locale =
      locale_from_params(conn) || locale_from_cookies(conn) || locale_from_request_headers(conn) ||
        locale_from_request_path(conn) || default_locale

    Gettext.put_locale(JobtodayWeb.Gettext, locale)

    conn
    |> put_session(:locale, locale)
  end

  @spec locale_from_params(Plug.Conn.t()) :: String.t() | nil
  defp locale_from_params(conn) do
    conn.params["locale"] |> validate_locale()
  end

  @spec locale_from_cookies(Plug.Conn.t()) :: String.t() | nil
  defp locale_from_cookies(conn) do
    conn.cookies["locale"] |> validate_locale()
  end

  @spec locale_from_request_path(Plug.Conn.t()) :: String.t() | nil
  defp locale_from_request_path(conn) do
    conn.params["country_code"] |> validate_locale()
  end

  @spec locale_from_request_headers(Plug.Conn.t()) :: String.t() | nil
  defp locale_from_request_headers(conn) do
    conn
    |> extract_accept_language()
    |> Enum.find(nil, fn accepted_locale ->
      Enum.member?(@supported_locales, accepted_locale)
    end)
  end

  @spec extract_accept_language(Plug.Conn.t()) :: List.t(String.t())
  defp extract_accept_language(conn) do
    case Plug.Conn.get_req_header(conn, "accept-language") do
      [value | _] ->
        value
        |> String.split(",")
        |> Enum.map(&parse_language_option/1)
        |> Enum.sort(&(&1.quality > &2.quality))
        |> Enum.map(& &1.tag)
        |> Enum.reject(&is_nil/1)
        |> ensure_language_fallbacks()

      _ ->
        []
    end
  end

  defp parse_language_option(string) do
    captures = Regex.named_captures(~r/^\s?(?<tag>[\w\-]+)(?:;q=(?<quality>[\d\.]+))?$/i, string)

    quality =
      case Float.parse(captures["quality"] || "1.0") do
        {val, _} -> val
        _ -> 1.0
      end

    normalized_tag = String.replace(captures["tag"], "-", "_")

    %{tag: normalized_tag, quality: quality}
  end

  defp ensure_language_fallbacks(tags) do
    Enum.flat_map(tags, fn tag ->
      [language | _] = String.split(tag, "-")
      if Enum.member?(tags, language), do: [tag], else: [tag, language]
    end)
  end

  @spec validate_locale(nil) :: nil
  defp validate_locale(nil), do: nil

  @spec validate_locale(String.t()) :: String.t() | nil
  defp validate_locale(locale) do
    is_complex_locale = String.contains?(locale, "-")
    normalized_locale = normalize_locale(locale, is_complex_locale)

    cond do
      normalized_locale in @supported_locales -> normalized_locale
      true -> nil
    end
  end

  defp normalize_locale("gb", _), do: "en"

  defp normalize_locale(locale, false), do: String.downcase(locale)

  defp normalize_locale(locale, true) do
    [lang, country] = String.split(locale, "-")
    "#{String.downcase(lang)}_#{String.upcase(country)}"
  end
end

```

so intitially markup has extracted locale from headers:
<img width="955" alt="image" src="https://github.com/elixir-gettext/gettext/assets/41234/c6168393-91f7-4e37-8d9c-b75bc40efdc6">

but on mount:
<img width="552" alt="image" src="https://github.com/elixir-gettext/gettext/assets/41234/e469a04c-a71a-4962-872f-0049f678cfa0">

**Comment by maennchen** [comment]
@itrelease The initial render of liveview and the socket rendered version don't work completely the same.

The initial render runs normally through your router and all plugs. But the socket version runs through the `socket` declared in your endpoint. That one does not run all your plugs.

Gettext persists the chosen language in the process dictionary. That does not work for a live view since the initial render and the web socket render are in different processes.

There's multiple ways to make sure that live view does the language correctly. I've personally used `ex_cldr` and its `Cldr.Plug.PutSession` plug. The session you can also read in your live view and set the locale accordingly.

You can see this used in an older project of mine (not the most current live view version): https://github.com/jshmrtn/hygeia/blob/main/lib/hygeia_web/live/init/locale.ex

Another way would be to pass the contents of `navigator.languages` to your `LiveSocket` `params` in JS and read that result.

To not repeat that same setup in every live view, [`on_mount`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#on_mount/1) can be used to only write the setup code once.

Phoenix also dedicated a whole guide on the topic: https://hexdocs.pm/phoenix_live_view/using-gettext.html#content

I'll close this issue since this is not a Gettext problem but more of an issue how phoenix / live view are being used.
