### ISSUE TITLE
Gettext extraction from non-Elixir sources

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-gettext/gettext#399]
For a liveview application I have a good junk of js as well, which I want to use gettext with as well to not need to deal with different translation systems. I found a tool to extract gettext messages from js, but now I'm wondering if this could be integrated with gettext for having one kind of commands for dealing with both sources. I'm especially interested in keeping `mix gettext.extract --check-up-to-date`, which the js tools doesn't do. It just extracts everything and creates a .pot file.

I'm imagining a simple behaviour, where implementations could be provided to gettext and those would be called by the extraction logic to provide additional messages before gettext does all it's downstream logic.

**Comment by maennchen** [comment]
The elixir gettext extractor is designed to be conscious of other tools. For example, by default unused messages are removed, but only if they have the `elixir-autogen` flag which means that they originated from the elixir library.

This is to ensure that multiple tools are able to work together efficiently.

Extracting foreign messages is not something that I believe should be part of the `gettext` library.

* The `gettext` library is focused to provide translations for elixir projects and I would consider this out of scope personally.
* Many tiny details are geared towards elixir.
  * For example: The message format flag when using the default interpolation is `elixir-format`. That would be wrong for a JS project.

However: The library `expo` is used in `gettext` for all the parsing / composing of `.po` files. You can build your own JS extracting library and write to the same file as `gettext`.

You'll find some examples on how to manipulate the `.po` files in the tests of `expo`:
https://github.com/elixir-gettext/expo/blob/761b35d385d76ef8469cc8dde37b4270471d568d/test/expo/po_test.exs#L15-L27

The check if a file changed is extremely simple:

https://github.com/elixir-gettext/gettext/blob/b41445ea04da137c62fb7ebc822fd8f05f2353fa/lib/gettext/extractor.ex#L254-L258

If we encounter a lot of duplicated code (`gettext` vs your custom extractor), I would be happy to migrate some common migration tooling from `gettext` to `expo` so that it can be used in other projects as well.

**Comment by LostKobrakai** [comment]
That seemed to have worked just fine. The library I use for parsing the JS also exposes the bare data besides being able to turn stuff into a .pot file. I just expose that data as json and the elixir file at compile time reads it and get those message ready for extraction by gettext. `Gettext.Extractor` is private api though. Would be interesting if there could be public api to know if the extractor is running and being able to provide e.g. `Expo.Message.*` structs to the extraction.

**Comment by maennchen** [comment]
> Would be interesting if there could be public api to know if the extractor is running and being able to provide e.g. Expo.Message.* structs to the extraction.

Let's wait for some feedback from the other maintainers to see how we should proceed. I personally don't think that we should offer that kind of API as part of this library.

**Comment by whatyouhide** [comment]
The `--check-up-to-date` flag for JS can be emulated by running the extraction and checking if any of the files changed, even using Git. I’m assuming you're doing this in CI so I think that would be just fine—after all it's what Gettext is doing more or less, or what `mix format --check-formatted` is doing too.

You can build your own `mix extract_all_translation` which calls `gettext.extract` and then your JS tool. Gettext for Elixir can already read the PO files generated by other tools, so you should be good there too.

Ultimately yeah I don't think we need any change in Gettext for Elixir here 🙃 

Thanks for the discussion @maennchen and @LostKobrakai 💟
