### ISSUE TITLE
Syntax errors can be absolutely terrible

### ISSUE THREAD

**Issue by whatyouhide** [elixir-gettext/gettext#89]
A PO file like this beauty (`default.po`):

``` po
#: lib/foo.ex:1
msgid "hello"

#: lib/foo.ex:2
msgid "world"
msgstr ""
```

Spits out a basically impossible-to-decipher error:

```
** (Gettext.PO.SyntaxError) 4: syntax error before: <<"#: lib/foo.ex:2">>
```

Why this sucks (as if it was need to show explicitly :stuck_out_tongue:):
- [x] no file name (wat!!!)
- [x] Erlang binary instead of Elixir binary
- [ ] finally, it should just say something like "missing `msgstr` for `msgid "hello"`"

@josevalim I'm afraid the only way to do this is to move the logic that builds translations from msgids and msgstrs outside of the `.yrl` parser, in Elixir-land? Wdyt?

**Comment by josevalim** [comment]
@whatyouhide it can be fixed, check how Elixir does it, but it is not pretty. :) In particular, if you can stick to erlang like tokens, things will be better.

**Comment by josevalim** [comment]
Actually, didn't you work on a PR in Elixir's parser to solve similar issues? :)

**Comment by whatyouhide** [comment]
@josevalim indeed I did this for char literals a few weeks ago in Elixir, but the Erlang representation here is just one of the problems. We can fix it by rewriting errors that match, e.g., `<<` but other than it not being pretty, it doesn't solve what I believe is a more important issue, which is that maybe we should probably just say "missing `msgstr` for `msgid "hello"`" as an error message instead of a plain syntax error. Wdyt?

**Comment by josevalim** [comment]
One option is to simplify the parsing to only parse lines, so it would
return a list of ["comment", "msgstr", "msgid"], and you would do the
grouping and post-validation later in a separate step.



*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
@josevalim sorry, I wasn't very clear earlier, but what you suggested is exactly what I meant with

>  I'm afraid the only way to do this is to move the logic that builds translations from msgids and msgstrs outside of the `.yrl` parser, in Elixir-land

:) I'll see what I can come up with. :smiley:

**Comment by tmbb** [comment]
NimbleParsec is oretty sweet for writing `.po` files amd by deafult it returns some pretty readable errors. I assume errors can be made even better with some careful grammar design.

I’m writing a `.po` file parser for my experimental translation library. If you’re interested, I can send you a link to the repo and even adapt the parser to work with Gettext.

**Comment by josevalim** [comment]
Oh, good call on Nimble for this. Please send us a link to the repo and we can continue the discussion from there.

**Comment by tmbb** [comment]
The parser is here: https://github.com/tmbb/mezzofanti/blob/master/lib/mezzofanti/gettext/gettext_parser.ex

The "grammar" is probably not complete. For example, it doesn't allow multiple strings as a way to represent multiline strings, and escaped characters inside strings aren't recognized correctly yet. It also assumes that the string to be translated appears only in a single location in the source code, but those are things you can change pretty easily. The repo contains some tests. The parser parses a `.pot` file into a list of translations, which are some custom structs my library uses.

### Rationale for my library (Mezzofanti, from a famous polyglot)

The main goal of the library is to be able to get translations from all applications running under a given BEAM instance. That way, the equivalent to `gettext.extract` could generate files to translate Ecto errors and stuff like that. But in order to have a backend for the translations, I've implemented a gettext parser and serializer.

The way I extract the translations from the other applications is the following:

* instead of importing `Mezzofanti` (the main public module), you must `use Mezzofanti`
* That will register a new module attribute which is persisted and accumulates all strings to be translated
* You mark all strings to be translated with the `translate/2` macro, which registers the strings (As well as some metadata) at compile time into said module attribute
* A `@before_compile` hook persists these translations into a special function, so that they can be retrieved later.

To create extract all translations (from all apps!) into a `.pot` file, you use the `mix mezzofanti.extract` task. That task starts all applications and iterates over all modules, looking for the "special function" that stores the translations.

It gathers all the translations and persists them into the `.pot` file.

You can build a Mezzofanti backend that will translate your UI based on that `.pot` file (and the respective `.po` files), and feed that backend into the other apps through a config option if appropriate. I still don't know how I want to do this

The backend generation part hasn't been implemented yet. I'm planning on supporting the ICU message format and I need to find a decent grammar to write a parser for that format, but the point is that it's easy to find a way to get the translations from all apps, and that idea could probably be used by gettext.

Anyway, this is a big rant and the important thing for now is the parser itself.

**Comment by josevalim** [comment]
Thanks @tmbb for the rationale. I may be missing something... but how is it different from `gettext("foo bar")` and `mix gettext.extract`? The mechanisms are very similar in that they rely on code execution (instead of static analysis).

**Comment by tmbb** [comment]
>  I may be missing something... but how is it different from gettext("foo bar") and mix gettext.extract? The mechanisms are very similar in that they rely on code execution (instead of static analysis).

Imagine have an application `my_app`, which depends on another application `my_dependency`.

I want to enable something like this, which gettext already allows:

```elixir
# * In :my_dependency
# file config.exs:
config :my_dependency,
  gettext_backend: MyDependency.MezzofantiBackend

# file lib/my_dependency/mezzofanti_backend.ex
defmodule MyDependency.MezzofantiBackend do
  use Mezzofanti.Backend
end

# file lib/my_dependency/some_module.ex
defmodule MyDependency.SomeModule do
  use MyDependency.MezzofantiBackend

  def x() do
    translate("my sentence", [])
  end
end

# * In :my_app
# file config.exs
config :my_dependency,
  gettext_backend: MyApp.MezzofantiBackend

# file lib/my_app/mezzofanti_backend.ex
defmodule MyApp.MezzofantiBackend do
  use Mezzofanti.Backend
end
```

The big difference is that when you run `mezzofanti.extract` inside `my_app`'s mix project, it will extract not only the translations in `my_app` (which `gettext` already does), but also the translations in `my_dependency` (which `gettext` can't do).

Basically, the "trick" is to add the translations into something more durable than a process that is only alive while compilation happens.
I've decided to store the translations into a special function in the modules.
To get all the translations in all applications, I just have to iterate over all modules inside all applications. The literal source code that does this is quite clear:

```elixir
  defp extract_translations_from_module(module) do
    try do
      module.__mezzofanti_translations__()
    rescue
      UndefinedFunctionError ->
        []
    end
  end

  @doc """
  Extract all translations from all the modules in all the applications.
  """
  def extract_all_translations() do
    applications = for {app, _, _} <- Application.loaded_applications(), do: app
    modules = Enum.flat_map(applications, fn app -> Application.spec(app, :modules) end)
    Enum.flat_map(modules, &extract_translations_from_module/1)
  end
```

**Comment by josevalim** [comment]
I see thanks!

So gettext can extract the translations to the dependency `priv` directory. Wouldn't it be simpler than to have a way to merge the dependency `pot` with the current project's `pot`?

**Comment by tmbb** [comment]
> So gettext can extract the translations to the dependency priv directory.

Gettext *would be able to* extract  the translations in the dependency into the main app's `priv` directory. I think that's what you mean.

>  Wouldn't it be simpler than to have a way to merge the dependency pot with the current project's pot?

I assume yuo mean *then* instead of *than* (otherwise I don't understand the question). Maybe, yeah. But that would require the package owner to generate and distribute the `.pot` when publishing the package. That's a manul step that can be forgotten, I guess. It doesn't seem as elegant as my approach. But it would be simpler for sure. Instead of leaving a footprint in your modules, it would store the translations in a file that can be read at compile time.

**Comment by tmbb** [comment]
The other reason I'm writing my own library is that I'd like to use the ICU message format instead of gettext's message format. I also don't like the `gettext`, `dgettext`, `ngettext` functions ver much and I'd prefer to have only a single `translate` macro for all cases, but that's just a syntax preference.

**Comment by josevalim** [comment]
> Gettext would be able to extract the translations in the dependency into the main app's priv directory. I think that's what you mean.

I actually meant what I said but what you propose could work too!

> That's a manul step that can be forgotten, I guess. 

I am thinking we can do it while we compile the project locally. :)

**Comment by whatyouhide** [comment]
This is not worth the effort for now. If we have complaints about the syntax error, we can revisit this, but to make the errors better there's quite a lot of work to do so calling it a day for now!
